server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderingsystem
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
#  type-alliases-package: com.itauge.entity