server:
  port: 8040
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderingsystem
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
